version: 2
jobs:
   build-linux:
     working_directory: ~/please
     docker:
       - image: thoughtmachine/please_ubuntu:20191202
     environment:
       PLZ_ARGS: "-p --profile ci"
     steps:
       - checkout
       - restore_cache:
           key: go-linux-main-v1-{{ checksum "third_party/go/BUILD" }}
       - run:
           name: Test
           command: ./pleasew test
       - store_test_results:
           path: plz-out/results
       - run:
           name: Package
           command: ./pleasew build //elan //mettle
       - persist_to_workspace:
           root: plz-out/bin
           paths:
             - elan/elan
             - mettle/mettle
       - store_artifacts:
           path: plz-out/log
       - save_cache:
           key: go-linux-main-v1-{{ checksum "third_party/go/BUILD" }}
           paths: [ "/.plz-cache/third_party/go" ]

   release:
     docker:
       - image: thoughtmachine/please_docs:20190318
     steps:
       - attach_workspace:
           at: /tmp/workspace
       - add_ssh_keys:
           fingerprints:
             - "cc:57:b9:67:31:65:a6:70:8c:e3:e7:90:ca:e6:a6:41"
       - run: /tmp/workspace/gen_release.pex /tmp/workspace/elan/elan /tmp/workspace/mettle/mettle

workflows:
  version: 2
  build-all:
    jobs:
      - build-linux
      - release:
          requires:
            - build-linux
          filters:
            branches:
              only: master
